import type { OptionType } from "./types";
import type { StylesConfig } from "react-select";

export const customSelectStyles: StylesConfig<OptionType, false> = {
  container: (base) => ({
    ...base,
    width: "100%",
  }),

  control: (base, state) => ({
    ...base,
    width: "100%",
    minHeight: "52px",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    borderColor: state.isFocused ? "#66d9ff" : "rgba(255, 255, 255, 0.12)",
    borderRadius: "16px",
    boxShadow: state.isFocused ? "0 0 0 1px #66d9ff" : "none",
    backdropFilter: "blur(10px)",
    transition: "all 0.2s ease",
    cursor: "pointer",
    "&:hover": {
      borderColor: "#66d9ff",
    },
  }),

  valueContainer: (base) => ({
    ...base,
    padding: "0 14px",
  }),

  input: (base) => ({
    ...base,
    color: "#ffffff",
  }),

  singleValue: (base) => ({
    ...base,
    color: "#ffffff",
  }),

  placeholder: (base) => ({
    ...base,
    color: "#718096",
  }),

  menuPortal: (base) => ({
    ...base,
    zIndex: 2000,
  }),

  menu: (base) => ({
    ...base,
    marginTop: "10px",
    borderRadius: "18px",
    overflow: "hidden",
    backgroundColor: "rgba(10, 17, 27, 0.98)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    boxShadow: "0 20px 50px rgba(0, 0, 0, 0.35)",
    backdropFilter: "blur(14px)",
    zIndex: 1600,
  }),

  menuList: (base) => ({
    ...base,
    padding: "8px",
  }),

  option: (base, state) => ({
    ...base,
    borderRadius: "12px",
    padding: "12px 14px",
    marginBottom: "4px",
    backgroundColor: state.isSelected
      ? "rgba(0, 170, 255, 0.22)"
      : state.isFocused
      ? "rgba(255, 255, 255, 0.06)"
      : "transparent",
    color: "#ffffff",
    cursor: "pointer",
    transition: "all 0.2s ease",
    ":active": {
      backgroundColor: "rgba(0, 170, 255, 0.24)",
    },
  }),

  dropdownIndicator: (base, state) => ({
    ...base,
    color: state.isFocused ? "#66d9ff" : "#718096",
    transition: "color 0.2s ease",
    "&:hover": {
      color: "#66d9ff",
    },
  }),

  clearIndicator: (base) => ({
    ...base,
    color: "#718096",
    "&:hover": {
      color: "#66d9ff",
    },
  }),

  indicatorSeparator: (base) => ({
    ...base,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
  }),

  noOptionsMessage: (base) => ({
    ...base,
    color: "#a0aec0",
    padding: "12px",
  }),
};

export const countryOptions: OptionType[] = [
  { value: "us", label: "United States" },
  { value: "pr", label: "Puerto Rico" },
  { value: "uk", label: "United Kingdom" },
  { value: "ca", label: "Canada" },
  { value: "au", label: "Australia" },
  { value: "de", label: "Germany" },
  { value: "fr", label: "France" },
  { value: "it", label: "Italy" },
  { value: "es", label: "Spain" },
  { value: "jp", label: "Japan" },
  { value: "cn", label: "China" },
  { value: "in", label: "India" },
  { value: "br", label: "Brazil" },
  { value: "za", label: "South Africa" },
  { value: "mx", label: "Mexico" },
  { value: "ru", label: "Russia" },
  { value: "kr", label: "South Korea" },
  { value: "nl", label: "Netherlands" },
  { value: "se", label: "Sweden" },
  { value: "no", label: "Norway" },
  { value: "fi", label: "Finland" },
  { value: "dk", label: "Denmark" },
  { value: "pl", label: "Poland" },
  { value: "pt", label: "Portugal" },
  { value: "sg", label: "Singapore" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "hk", label: "Hong Kong" },
  { value: "tw", label: "Taiwan" },
  { value: "ng", label: "Nigeria" },
  { value: "ke", label: "Kenya" },
  { value: "ar", label: "Argentina" },
  { value: "cl", label: "Chile" },
  { value: "co", label: "Colombia" },
  { value: "ve", label: "Venezuela" },
  { value: "th", label: "Thailand" },
  { value: "my", label: "Malaysia" },
  { value: "ph", label: "Philippines" },
  { value: "vn", label: "Vietnam" },
  { value: "cz", label: "Czech Republic" },
  { value: "hu", label: "Hungary" },
  { value: "ro", label: "Romania" },
  { value: "bg", label: "Bulgaria" },
  { value: "sk", label: "Slovakia" },
  { value: "si", label: "Slovenia" },
  { value: "lt", label: "Lithuania" },
  { value: "lv", label: "Latvia" },
  { value: "ee", label: "Estonia" },
  { value: "is", label: "Iceland" },
  { value: "mt", label: "Malta" },
  { value: "cy", label: "Cyprus" },
  { value: "by", label: "Belarus" },
  { value: "ua", label: "Ukraine" },
  { value: "kz", label: "Kazakhstan" },
  { value: "uz", label: "Uzbekistan" },
  { value: "az", label: "Azerbaijan" },
  { value: "ge", label: "Georgia" },
  { value: "am", label: "Armenia" },
  { value: "md", label: "Moldova" },
  { value: "tj", label: "Tajikistan" },
  { value: "tm", label: "Turkmenistan" },
  { value: "kg", label: "Kyrgyzstan" },
  { value: "np", label: "Nepal" },
  { value: "bd", label: "Bangladesh" },
  { value: "lk", label: "Sri Lanka" },
  { value: "mm", label: "Myanmar" },
  { value: "la", label: "Laos" },
  { value: "kh", label: "Cambodia" },
  { value: "bt", label: "Bhutan" },
  { value: "mv", label: "Maldives" },
  { value: "mn", label: "Mongolia" },
  { value: "af", label: "Afghanistan" },
  { value: "ir", label: "Iran" },
  { value: "iq", label: "Iraq" },
  { value: "sy", label: "Syria" },
  { value: "ye", label: "Yemen" },
  { value: "sd", label: "Sudan" },
  { value: "ly", label: "Libya" },
  { value: "dz", label: "Algeria" },
  { value: "ma", label: "Morocco" },
  { value: "tn", label: "Tunisia" },
  { value: "eg", label: "Egypt" },
  { value: "ci", label: "Ivory Coast" },
  { value: "gh", label: "Ghana" },
  { value: "tz", label: "Tanzania" },
  { value: "ug", label: "Uganda" },
  { value: "zm", label: "Zambia" },
  { value: "zw", label: "Zimbabwe" },
  { value: "sc", label: "Seychelles" },
  { value: "mu", label: "Mauritius" },
  { value: "bw", label: "Botswana" },
  { value: "na", label: "Namibia" },
  { value: "ls", label: "Lesotho" },
  { value: "sz", label: "Eswatini" },
  { value: "cv", label: "Cape Verde" },
  { value: "gm", label: "Gambia" },
  { value: "sl", label: "Sierra Leone" },
  { value: "lr", label: "Liberia" },
  { value: "ne", label: "Niger" },
  { value: "ml", label: "Mali" },
  { value: "sn", label: "Senegal" },
  { value: "dj", label: "Djibouti" },
  { value: "so", label: "Somalia" },
  { value: "et", label: "Ethiopia" },
  { value: "cm", label: "Cameroon" },
  { value: "tg", label: "Togo" },
  { value: "gq", label: "Equatorial Guinea" },
  { value: "st", label: "Sao Tome and Principe" },
  { value: "ao", label: "Angola" },
  { value: "mz", label: "Mozambique" },
  { value: "bi", label: "Burundi" },
  { value: "rw", label: "Rwanda" },
  { value: "other", label: "Other" },
];

export const referralOptions = [
  { value: "instagram", label: "Instagram" },
  { value: "facebook", label: "Facebook" },
  { value: "tiktok", label: "TikTok" },
  { value: "youtube", label: "Youtube" },
  { value: "twitch", label: "Twitch" },
  { value: "mixcloud", label: "Mixcloud" },
  { value: "friend", label: "Friend" },
  { value: "radio", label: "Radio" },
  { value: "other", label: "Other" },
];
